### ISSUE TITLE
Frontend Bauen & Gestalten

### ISSUE THREAD

**Issue by jblakshman** [ID-Start-Winter22/SoundBot#10]
Die Seite, auf der unser SoundBot läuft soll visuell gestaltet und verschönert werden

**Comment by leostraub** [comment]
Ich hab das Frontend vom SoundBot vorläufig gestaltet.
Banner, Icon und Schrift sind eingefügt und die Seite an die Farbpalette angepasst.

![Bildschirm­foto 2022-12-19 um 20 11 48](https://user-images.githubusercontent.com/115628643/208501947-138f1d34-d56a-4f79-aeee-0d0cc48598e1.jpg)

**Comment by leostraub** [comment]
## Ziele für das Frontend
- Skalierbarkeit der Seite
- Link zu GitHub

**Comment by leostraub** [comment]
## Neues Frontend
Ich hab das Frontend vom SoundBot vorläufig gestaltet.
Die Seite an die SoundBot Farbpalette angepasst sowie Icon und Banner eingefügt. 

![Bildschirm­foto 2022-12-19 um 20 11 48](https://user-images.githubusercontent.com/115628643/208501947-138f1d34-d56a-4f79-aeee-0d0cc48598e1.jpg)

**Comment by leostraub** [comment]
## Ziele für das Frontend
- Skalierbarkeit der Seite
- Link zu GitHub

**Comment by leostraub** [comment]
# Neues Layout
![Bildschirm­foto 2022-12-23 um 02 11 00](https://user-images.githubusercontent.com/115628643/209251465-c189b91b-18b1-4518-9310-a0565b11ea4d.jpg)

**Comment by leostraub** [comment]
# Neues Layout
![Bildschirm­foto 2022-12-28 um 14 08 32](https://user-images.githubusercontent.com/115628643/209817091-a5b4be7f-ad8d-4cda-bca0-3cc39a4705fe.jpg)
