### ISSUE TITLE
Wiki-Seite & Readme neu gestalten

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#16]
Wiki:
- neuer Banner
- Infos zum Bot (Was ist der SoundBot?, Was kann der Bot aktuell?, Was ist noch geplant?, Was kann der Bot nicht?)

Readme gestalten: 
- Banner, Link zu Wiki und Beschreibungstext zum SoundBot

**Comment by leostraub** [comment]
## Neu hinzugefügt:
Infos zum Bot (Was ist der SoundBot?, Was kann der Bot aktuell?, Was ist noch geplant?, Was kann der Bot nicht?)
Banner neu gestaltet
Readme neu gestaltet

**Comment by leostraub** [comment]
@SchlechtePoesieIstProgramm  bitte bei Gelegenheit kurz die Texte zum Bot im Wiki lesen, überprüfen und anpassen falls sich was ändert.

**Comment by SchlechtePoesieIstProgramm** [comment]
Hab ich mir angeschaut. Sieht gut aus
