### ISSUE TITLE
Usability Testing

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#18]
## Aufgabe
Erstellen Sie ein Skript (Ablaufplan - Vorlage auf Miro) für ein Usability/Concept Testing und führen Sie mind. 3 Testings durch. Testen Sie den Chatbot mit ihrer Zielgruppe/ Nutzenden (ideal) oder (zur Not) mit Freunden und Familie. In der Lehrveranstaltung testen Sie mit einem anderen Team, welches Ihnen zugewiesen wird. Dokumentieren Sie die Ergebnisse der Usability Tests (Fotos und Text) und beschreiben Sie, was Sie an ihrem Chatbot verbessern sollten. Führen Sie die Verbesserungen durch.

**Comment by leostraub** [comment]
## Aufgabe
Erstellen Sie ein Skript (Ablaufplan - Vorlage auf Miro) für ein Usability/Concept Testing und führen Sie mind. 3 Testings durch. Testen Sie den Chatbot mit ihrer Zielgruppe/ Nutzenden (ideal) oder (zur Not) mit Freunden und Familie. In der Lehrveranstaltung testen Sie mit einem anderen Team, welches Ihnen zugewiesen wird. Dokumentieren Sie die Ergebnisse der Usability Tests (Fotos und Text) und beschreiben Sie, was Sie an ihrem Chatbot verbessern sollten. Führen Sie die Verbesserungen durch.

**Comment by jblakshman** [comment]
Usability Testing mit 2 Personen werden von mir durchgeführt und dokumentiert.

**Comment by jblakshman** [comment]
Das Usability Testing wurde mit drei Personen abgeschlossen und auf dem Miroboard dokumentiert.

**Comment by SchlechtePoesieIstProgramm** [comment]
Würde sagen das passt so
