### ISSUE TITLE
Creative Vision (Page / Poster)

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#20]
## Aufgabe:
Gestalten Sie für den Chatbot ein digitales Zuhause (Creative Vision), z.B. in Form einer Page / Poster.

**Comment by leostraub** [comment]
kann auf der Frontend website #10  umgesetzt werden.

**Comment by leostraub** [comment]
@SchlechtePoesieIstProgramm bitte überprüfen und schließen

**Comment by SchlechtePoesieIstProgramm** [comment]
Frontend passt
