### ISSUE TITLE
Funktion "Ähnliche Interpreten" fixen

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#21]
Die Funktion kann aktuell nur mit wenigen Interpreten wie Michael Jackson, Metallica, Lorna Shore, Frost Clad ausgeführt werden.  Bis ende Sprint 2 sollten beliebige Interpreten abrufbar sein.

**Comment by leostraub** [comment]
Mehr Infos zu Artist ausgeben (Link, Bild, Gerne)

**Comment by SchlechtePoesieIstProgramm** [comment]
Das funktioniert für den Prototyp gut genug

**Comment by jblakshman** [comment]
Es wurden mehrere Beispiele hinzugefügt.
