### ISSUE TITLE
Infos zu Interpreten

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#22]
Info für einzelne Interpreten abrufbar.

## Bespiel: 

[ Infos zu Interpreten ] Button

### Nutzer:  
Michael Jackson

### Bot: 
Michael Jackson war ein berühmter amerikanischer Sänger, Songwriter und Tänzer. Er wurde 1958 geboren und wurde in den 1970er und 1980er Jahren zu einem der weltweit bekanntesten und erfolgreichsten Musiker. Er verkaufte mehr als 750 Millionen Tonträger und gewann zahlreiche Auszeichnungen, darunter 13 Grammy Awards. Jackson wurde vor allem durch seine Hit-Songs wie "Thriller", "Beat It", "Billie Jean" und "Man in the Mirror" bekannt. Er war auch bekannt für seine einzigartigen Tanzfähigkeiten und seine innovativen Musikvideos. Er starb im Jahr 2009 im Alter von 50 Jahren.

### Nutzer:  Cool!

**Comment by SchlechtePoesieIstProgramm** [comment]
Das wäre erledigt. Kann ja mal einer drüber schauen
