### ISSUE TITLE
Abschlussräsentation zusammenstellen

### ISSUE THREAD

**Issue by jblakshman** [ID-Start-Winter22/SoundBot#33]
Die Abschlusspräsentation muss geplant, erstellt und auf alle Gruppenmitglieder aufgeteilt werden.

**Comment by leostraub** [comment]
https://docs.google.com/presentation/d/1YXq7ie7BoBIS-KY_MPDIVqhGdRh-4D1kZhW8yJwRU4g/edit?usp=sharing
