### ISSUE TITLE
implementieren der "Ähnliche Songs"

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/SoundBot#7]
implementieren der "Ähnliche Songs"

wenn der Nutzer dem bot einen Song der ihm gefällt mitteilt werden dem Nutzer ähnliche Songs vorgeschlagen.

**Comment by SchlechtePoesieIstProgramm** [comment]
Die ähnlichen Artists sind eingefügt, kann ja mal jemand drüber schauen

**Comment by leostraub** [comment]
Passt

**Comment by SchlechtePoesieIstProgramm** [comment]
Das wird für den Prototyp nicht mehr möglich sein
